name: Auto Publish NPM

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: NpmjsWorker 

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Setup Git identity
        run: |
          git config --global user.name "c4bal[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Bump version
        run: |
          npm version patch -m "chore: bump version to %s [skip ci]"
          git push

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
